### ISSUE TITLE
Для першай ітэрацыі. Эпік. Задача для UX спецыяліста

### ISSUE THREAD

**Issue by rizomaa** [konstbel/landing#1]
Тут дэтальна апісана

- [x] Брэндбук (фирмовы стыль)
- [x] Схемы старонак і блокаў (галоўная, апісанне, блог, як ладучыцца, падпіскі)
- [x] Дызайна старонак.

Тут дэталі
https://docs.google.com/document/d/1prGzLQEJFxRk8e0XbJsmvkDOK6FPoFsnZC8Dun-l8t4/edit?usp=sharing

**Comment by rizomaa** [comment]
![лога7](https://user-images.githubusercontent.com/9870374/73091542-b26dd300-3eeb-11ea-906c-ef55a45c0ca1.png)

**Comment by rizomaa** [comment]
вось скінулі цікавы артыкул http://mirymir.by/simbols.html

**Comment by syromolotovpavel** [comment]
https://www.figma.com/file/xfVGDWdrnXV0U1iuNifiue/%D0%9A%D0%B0%D0%BD%D1%81%D1%82%D1%8B%D1%82%D1%83%D1%86%D1%8B%D1%8F.%D0%B1%D0%B5%D0%BB-0.1?node-id=0%3A1

**Comment by rizomaa** [comment]
- [x] - спрасціць шаблоны
- [x] - намаляваць схематычна галоўную
- [x] - дадаць пераключальнікі моваў.

**Comment by rizomaa** [comment]
[CВ 1.pdf](https://github.com/konstbel/landing/files/4167009/C.1.pdf)
[CВ.zip](https://github.com/konstbel/landing/files/4167013/C.zip)
@syromolotovpavel змог раздабыць яшчэ па візуалцы, глянь
