### ISSUE TITLE
Чаму "Статычныя старонкі"

### ISSUE THREAD

**Issue by rielas** [konstbel/landing#15]
Чаму варта выкарыстоўваць статычныя старонкі:

1. Нам не трэба думаць наконт хостынга — статычныя старонкі можна хосціць дзе заўгодна. Нават на гітхабе.
2. Падыходзіць для асноўнай функцыі лэндынга: старонкі апісання праекту.
3. Вельмі проста і хутка працуе. З гэтага чынніка статычны сайт вельмі цяжка пакласці. Вельмі маленькая паверхня атакі — нашмат цяжэй узламаць.

**Hugo** быў абраны з-за яго папулярнасці: болей за ўсіх зорак на гітхабе. Працуе вельмі хутка ў параўнанні з **Jekyll**.

**Comment by rizomaa** [comment]
@rielas што будзем рабіць, калі з'явіцца стужка навінаў (яна з'явіцца хутка, бо гэта перая ітэрацыя)

**Comment by rielas** [comment]
Яна ўжо [даступна](https://konstbel.github.io/landing/posts/). Навіны можна класці ў дырэкторыю [posts](https://github.com/konstbel/landing/tree/master/content/posts).

**Comment by rizomaa** [comment]
@rielas > Яна ўжо [даступна](https://konstbel.github.io/landing/posts/). Навіны можна класці ў дырэкторыю [posts](https://github.com/konstbel/landing/tree/master/content/posts).

дзякуй. можаш напісаць алгарытм як з ім працаваць звычайным рэдактарам. не тэхнарам (як мы сёння падчас сустрэчы мелі справу)

**Comment by rielas** [comment]
Зрабіў форк і дадаў Netlify CMS - убудаваны рэдактар для блога. Можна паспрабаваць на [тэставам хостынгу](https://confident-ardinghelli-605279.netlify.com/admin/#/). Калі гэта норм, то нам не трэба нічога тлумачыць - інтэрфейс як у звычайнай CMS

**Comment by rizomaa** [comment]
@rielas як я магу дадаць пост у новы блог?
