### ISSUE TITLE
Старонка "Як далучыцца"

### ISSUE THREAD

**Issue by rizomaa** [konstbel/landing#17]
Пытанні для фарміравання старонкі як далучыцца

- [x] 1. Ці ёсць кантэнт для старонкі (тэкст, фота)?
- [x] 2. З кім звязацца наконт кантэнта для гэтай старонкі?3. 
- [x] 4. Калі няма і па 1 і 2 пытанні? Што павінна быць на старонцы?

- [x] Макет
- [x] Дизайн
- [x] Адаптивный версия

Визуальная часть лежит тут:
https://www.figma.com/file/xfVGDWdrnXV0U1iuNifiue/%D0%9A%D0%B0%D0%BD%D1%81%D1%82%D1%8B%D1%82%D1%83%D1%86%D1%8B%D1%8F.%D0%B1%D0%B5%D0%BB-v1?node-id=0%3A1

Актуальны кантэнт тут: https://docs.google.com/document/d/12TEPtlSj4UKirzq3xS1slyTdJ8tNvLfvpu_-TM7UAIU/edit

**Comment by rizomaa** [comment]
Кантэнт

Чем можно помочь?

Сейчас главное – это присоединение к платформе. Присоединяйтесь и зовите тех, кому важна независимость Беларуси.

Где я могу следить за кампанией?

Прежде всего можно использовать нашу платформу: канстытуцыя.бел. Также присоединяйтесь к нам в социальных сетях и мессенджерах.

Хэштег кампании — #незалежнасць

Чем можно помочь?

Сейчас в общественной кампании в защиту независимости "Свежий ветер" (канстытуцыя.бел) работают несколь групп волонтеров, решающих разные задачи:

1) Редакторская группа (редакторы, журналисты, капирайтэры, эксперты): написание статей, аналитики, заявлений. Координатор: Михаил Янчук (контакт в Telegram @MichalJanczuk);

2) Креативная группа (дизайнеры, художники, специалисты по инфографике, креативщики): создание визуального ряда, картинок, инфографики, мотиваторов, демотиваторов. Координатор: Юля Лисица (контакт в Telegram @jula_harbunova);

3) Группа видео (специалисты по видео-контенту, журналисты): ролики, видео-обращения, интервью, анимация. Координатор: Ася Дорофеева (контакт в Telegram @asia_darafeeva);

4) Модераторская группа (модераторы групп в соц сетях и мэсэнжарах): распространение контента компании, организация коммуникации с участниками кампании. Координатор: Андрей Шутов (контакт в Telegram @andreischutt);

5) Коммуникативная группа (комментарии, лайки, распространение, действия в других сообществах социальных сетей). Координатор: Кайн (контакт в Telegram @RexAlherd);

6) Техническая группа (программисты, web-дизайнеры, аналитики). Координатор: Karuzlik Charavaty (контакт в Telegram @karuzlik);

Всем группам нужна ваша помощь! К работе всех можно присоединяться через их координаторов или написав нам на почту: kanstytucyja.bel@gmail.com.

Нам очень нужна ваша поддержка!

Что еще я могу сделать?

Самое простое – это присоединение к платформе и распространение информации. Присоединяйтесь к нам, репостите наши материалы в социальных сетях и зовите к нам тех, кому важна независимость Беларуси.

Таже можно направить обращение к Премьер-министру Беларуси.

Краткая инструкция

А) Если отправлять почтой, то необходимо:

1. Вставить в шаблон обращения свой адрес, ФИО, и дату;

2. В текст обращения можно что-нибудь добавить от себя;

3. Распечатать и подписать снизу.

4. Отправить почтой по адресу: 220010, Республика Беларусь, г. Минск, ул. Советская, 9

5. Отправлять лучше с письмом с уведомлением. То есть нужно взять на почте такую жёлтенькую бумажку, где написать свой обратный адрес. Эта бумажка потом придет по месту вашего жительства и будет являться подтверждением того, что они получили ваше обращение и имеют максимум 30 дней для ответа.

Б) Для электронного обращения нужно воспользоваться формой по ссылке: http://www.government.by/.

Ссылка на шаблон обращения: https://docs.google.com/.

**Comment by rizomaa** [comment]
Новы кантэнт для старонкі "Як далучыцца"

Мы хотим, чтобы большинство граждан Беларуси открыто высказалось против любых попыток торга суверенитетом страны! Чтобы не допустить этого торга, нам нужно не позволить власти украсть очередные выборы и тайно переписать Конституцию Беларуси для последующей продажи страны Москве!

Мы хочам, каб большасць грамадзян Беларусі адкрыта выказалася супраць любых спробаў гандлю суверэнітэтам краіны! Каб не дапусціць гэтага гандлю, нам трэбе не дазволіць уладам скрасці чарговыя выбары і патаемна перапісаць Канстытуцыю Беларусі для наступнага продажу краіны Маскве!

Нас можно поддержать через краудфандинг: https://www.talaka.org/projects/3341 

Нас можна падтрымаць шляхам краўдфандынгу: https://www.talaka.org/projects/3341

Присоединяйтесь к нам в соцсетях и мессенджерах:

Далучайцеся да нас у сацыяльных сетках і мэсэнджарах:

• YouTube: https://youtube.com/c/Свежывецер
• Facebook: https://www.facebook.com/svezhyvecer
• Telegram: https://t.me/svezhyvecer
• ВКонтакте: https://vk.com/svezhyvecer
• Одноклассники: https://ok.ru/svezhyvecer
• Viber: https://bit.ly/2mr6RaI
• Twitter: https://twitter.com/svezhyvecer
• Instagram: https://instagram.com/constitution_be...

Хэштэгі кампаніі — #незалежнасць #дурыбары2020

**Comment by syromolotovpavel** [comment]
- [ ] Макет
- [ ] Дизайн
- [ ] Адаптивный версия

**Comment by rizomaa** [comment]
![v1 1-how-to-join](https://user-images.githubusercontent.com/9870374/74723704-11eda300-524c-11ea-89b0-ac7e6bddf245.png)

**Comment by rizomaa** [comment]
гэту таксама зачыняю
