### ISSUE TITLE
UI kit для сайта (частка брэндбука)

### ISSUE THREAD

**Issue by rizomaa** [konstbel/landing#19]
Прыклады:

- https://wiki.falanster.info/wiki/Брэнд_Doika
- https://wiki.falanster.info/wiki/Брэнд_Doika

**Comment by syromolotovpavel** [comment]
![73091581](https://user-images.githubusercontent.com/60265148/76141247-a173be00-6062-11ea-9634-1ad041fa5334.png)

**Comment by syromolotovpavel** [comment]
https://www.figma.com/file/xfVGDWdrnXV0U1iuNifiue/%D0%9A%D0%B0%D0%BD%D1%81%D1%82%D1%8B%D1%82%D1%83%D1%86%D1%8B%D1%8F.%D0%B1%D0%B5%D0%BB-v1?node-id=435%3A2

**Comment by syromolotovpavel** [comment]
https://www.figma.com/file/xfVGDWdrnXV0U1iuNifiue/%D0%9A%D0%B0%D0%BD%D1%81%D1%82%D1%8B%D1%82%D1%83%D1%86 % D1% 8B% D1% 8F.% D0% B1% D0% B5% D0% BB-V1? узел-ID = 435% 3A2
