### ISSUE TITLE
Распрацоўка Галоўнай старонкі

### ISSUE THREAD

**Issue by rizomaa** [konstbel/landing#20]
- [x] 1. Прагаварыць патрэбу
- [x] 2. Абмеркаваць макет.
- [x] 3. Намаляваць яго.
- [x] 4. Адаптивный веб-дизайн
- [x] 5.1 Завярстаць мабільную
- [x] 5.2 Завярстаць дэсктопную версію
- [x] 6. Шабланизаваць для шматмоўнасці

Визуальная часть лежит тут:
https://www.figma.com/file/xfVGDWdrnXV0U1iuNifiue/%D0%9A%D0%B0%D0%BD%D1%81%D1%82%D1%8B%D1%82%D1%83%D1%86%D1%8B%D1%8F.%D0%B1%D0%B5%D0%BB-v1?node-id=0%3A1

Актуальны кантэнт тут: https://docs.google.com/document/d/12TEPtlSj4UKirzq3xS1slyTdJ8tNvLfvpu_-TM7UAIU/edit

**Comment by rizomaa** [comment]
![photo_2020-02-02_23-22-30](https://user-images.githubusercontent.com/9870374/73614755-03c84180-4613-11ea-94b5-e8f5e43e2948.jpg)

**Comment by rizomaa** [comment]
Чакаем па кантэнту:


1. Усё на рускай і беларускай мовах.

1.1. Галоўная старонка - Лаканічна Апісанне пра кампанію (поўная версія на старонцы "Пра нас")

1.2. Галоўная старонка - Таймлайн (тут мы пакуль не ў курсе, але вы заявілі гэтую секцыю)

1.3. Галоўная старонка - Лаканічна "Як далчыцца" (пощная версія будзе на старонцы "Як далучыцца").

@syromolotovpavel

**Comment by rizomaa** [comment]
Актуальны кантэнт тут: https://docs.google.com/document/d/12TEPtlSj4UKirzq3xS1slyTdJ8tNvLfvpu_-TM7UAIU/edit

**Comment by rizomaa** [comment]
Пакуль таймлайн не чакаем і робім без яе

**Comment by rizomaa** [comment]
стварай тэчку для дызайна theme
@ioann-claudius

**Comment by rizomaa** [comment]
@ioann-claudius яшчэ пачынай з мабільнай весіі вястаць

**Comment by ghost** [comment]
Подобрал более-менее похожие темы из сета [hugo](https://themes.gohugo.io/). Попадания 10 из 10 на мой взгляд не было, но эти можно будет использовать в случае чего.

1. [Hugo-assembly](https://themes.gohugo.io/hugo-assembly/)
2. [Dot](https://themes.gohugo.io/dot-hugo-documentation-theme/)
3. [Ananke gohugo theme](https://themes.gohugo.io/gohugo-theme-ananke/)
4. [Influencer](https://themes.gohugo.io/theme/Influencer-hugo/)

Первые три - достаточно простые темы без лишних элементов. Думаю, что при необходимости можно будет быстренько доверствать недостающие детали. Influencer же, напротив, содержит большой набор элементов, лишние из которых можно будет вырезать

**Comment by rizomaa** [comment]
@ioann-claudius дзякуй за даследванне=) Гэта харошы крок наперад_

**Comment by rizomaa** [comment]
дызайн ад  @syromolotovpavel 
![v1 1-main](https://user-images.githubusercontent.com/9870374/74718383-28dbc780-5243-11ea-81ad-78dd600da19b.png)

можна абмяркоўваць

**Comment by rizomaa** [comment]
https://www.figma.com/file/xfVGDWdrnXV0U1iuNifiue/Канстытуцыя.бел-v1?node-id=0%3A1

**Comment by alherd-by** [comment]
#61
