### ISSUE TITLE
Организация интернационализации сайта

### ISSUE THREAD

**Issue by alherd-by** [konstbel/landing#26]
- [x] текст на статичных страницах(все что не блог) нужно заменить на плейсхолдеры текст которых будет подставлятся в зависимости от языка
- [x] настроить hugo
- [x] редактирование файлов переводов не-технарями (?)
- [x] домены
- [x] URL страниц. Github pages не позволит нам отобразить https://домен.by на всех языках.
Придется делать либо https://домен.by/be, https://домен.by/en либо перезжать на другой хостинг и там настраивать отдельно веб сервер.

https://www.klaasnotfound.com/2017/02/16/proper-multilingual-site-with-github-pages-and-jekyll/

**Comment by rielas** [comment]
Давайце апішу як i18n робіцца ў бягучым варыянце:

1. Асабістыя старонкі, якія маюць версіі на [расейскай](https://github.com/rielas/landing/blob/master/content/ru/about/_index.md) і [беларускай](https://github.com/rielas/landing/blob/master/content/be/about/_index.md) мовах.

2. Файлы с плэйсхолдэрамі для шаблонаў для [be](https://github.com/rielas/landing/blob/master/themes/ananke/i18n/be.toml) і [ru](https://github.com/rielas/landing/blob/master/themes/ananke/i18n/ru.toml).

У карыстальнікаў адмінкі ёсць магчымасць дадаваць версіі старонак на абедзвюх мовах і рэдагаваць іх.

**Comment by rielas** [comment]
Бягучая сітуацыя з url-амі:

Расейская версія з'яўляецца дэфолтнай і ляжыць наўпрост па `/`. Беларуская ляжыць на `/be/`. Ёсць баг, што з беларускай версіі старонак спасылкі вядуць на расейскую версію

**Comment by rizomaa** [comment]
@alg3rd апішы які тут прагэс...

я вывеў на асобную ішшу задачу па фіксу спасылак на бел мове. https://github.com/konstbel/landing/issues/35
калі яна будлюе гэту ішу закрый калі ласка яе

**Comment by alherd-by** [comment]
Все вопросы решены. 
По поводу редактирования файлов переводов - не так актуально т.к. 95% контента доступны в cms . Остальное не будет так часто менятся
