### ISSUE TITLE
Дыяграма архітэктуры

### ISSUE THREAD

**Issue by antonzhyliuk** [konstbel/landing#28]
Трэба графічная схема на якой будуць выяўлены асноўныя кампаненты сыстэмы

- [ ]  улічыць маштабуемасць (даданне дадатковых сэрвісаў)
- [ ]  кошт (грошы на сэрвісы, час развіцця і падтрымку).
- [ ]  прастата кіравання.

**Comment by alherd-by** [comment]
Элементы:
1) github | github actions - source code/ CI / хранилище статического контента
2) production сервер (в данный момент хостинг на netlify)
3) сервер для админки https://github.com/marmelab/react-admin /api 

конституция.бел - это статичный сайт, сгенерированный hugo на основании контента описанный в маркдауне, который вносится посредством отдельной админки.

~~Админка, также будет выполнять роль бэкенда, с которым сайт будет связывать по API~~
Админка нужна будет как интерфейс для API. 

API сервер. На нем непосредственно будут происходить рассылки(пуш/email). Возможно, в будущем, тут будет происходить редактирования сложного контента, если редактор на netlify не будет справлятся

Обновление контента сайта будет происходить посредством запуска CI по каждому коммиту в мастер. (Согласовать с @rielas процесс CI|CD)

По масштабированию:
В случае если нам понадобится сделать какой-нибудь сложный интерфейс, мы сможем в случае чего добавить интерфейс на JS.

**Comment by rizomaa** [comment]
@alg3rd 

у чым плюсы (і мінусы) гэтай архітэктуры ў параўнанні з устаноўленым wordpress + шаблоны + плагіны да яго. 
Наколькі  паказаў пошук, гэта усё там ёсць (у любым разе пагутарым на сустрэчы)

**Comment by antonzhyliuk** [comment]
Вось супер схематычная дыяграма якую варта ўдакладніць, заўтра абмяркуем на сустрэчы
![image](https://user-images.githubusercontent.com/5443338/74574606-4b48b900-4f95-11ea-9836-26b97db9fde1.png)
Маляваў пальцам, таму троху крыва)

Сіні квадрат зьверху - гэта наш фронт-енд з інтерфейсам (UI), тое што будзе бачыць і куда будзе тыкаць юзер. Гэта будзе js прыкладаньне якое распаўсюджваецца зь дапамогай якой-небудзь сеткі распаўсюду кантэнту (CDN). 

Сіні квадрат зьнізу - гэта наш бэк-енд, гэта сервер які адказвае за кіраваньне дадзеннымі, на ём будзе усталявана база дадзенных (DB) і сервіс (BE) які будзе стасавацца з UI праз http пратакол і стасавацца зь сервісамі трэццяй стараны (сіні квадрат зьнізу справа), напрыклад з sendgrid і існуючым прыкладаньнем канстытуцыя.бел. Яшчэ там будзе разьмешчаны наш CI сервіс які будзе набываць зыходныя коды з github (сіні квадрат зьнізу злева) і білдзіць сістэму.

**Comment by alherd-by** [comment]
> @alg3rd
> 
> у чым плюсы (і мінусы) гэтай архітэктуры ў параўнанні з устаноўленым wordpress + шаблоны + плагіны да яго.
> Наколькі паказаў пошук, гэта усё там ёсць (у любым разе пагутарым на сустрэчы)

Плюсы
- Высокая произодительность | Масштабируемость
- Простота разворачивания
- Безопасность
- Современность
- Наличие самых различных интеграций по типу Netlify
- Хостинг 

Минусы
- практически невозможно сделать возможность разграничения доступов. Но я думаю в нашем случае это не понадобиться.

**Comment by rizomaa** [comment]
Задачу зачыняю, але далучаю да дэплоймэнта... бо там яшчэ няясна
