### ISSUE TITLE
Напісаць гайд працы рэдактараў з адмінкай сайта на першым этапе.

### ISSUE THREAD

**Issue by rizomaa** [konstbel/landing#29]
Рэдактар можа:
1. Рэдагаваць статычныя старонкі (пра нас, як далучыцца) на рускай і беларускай мовах.
2. Дадаваць/выдаляць старонкі блога.
3. Змяняць старонкі блога.
4. Дадаваць рускую і беларускую версію матэрыялаў і у блог.
5. Заходзіць і выходзіць з адмінкі

Зрабіць апісанне з назвамі палёў шаблонаў рэдагавання, каб рэдактар не мог заблытацца наогул

**Comment by rizomaa** [comment]
@Crashtown @rielas калі ласка скаардынуйцеся, каб у вас было агульнае разуменне як паводзіць карыстальнік у блогу. 
@Crashtown ці усё функцыі рэдактара на месцы?

**Comment by rielas** [comment]
Давайце тады я вазьму на сябе смеласць змержыць [гэты PR](https://github.com/konstbel/landing/pull/27) спачатку

**Comment by rizomaa** [comment]
@rielas 

магчыма ты лічыш нявартым зараз апісваць дзеянні канечнага карыстальніка ў дэталях.

Але я адчуваю, што 
1. ў кодынгу вы хутка пайшлі наперад і 
2. не высветлілі архітэктурныя пытанні
3. асабліва (!!!) зручнасць для фінальнага карыстальніка (бо я пакуль не бачу які дзеянні фінальнаму карыстальніку трэба будзе рабіць, каб выкарыстоўваць сістэму па прызначэнню), 
4. а таксама прапарцыянальнасць затрачанага часу на распрацоўку нечага новага або выкарыстанне існуючых тэхналогій з адаптацыяй.

Можаш  улучыцца ў https://github.com/konstbel/landing/issues/3#issuecomment-584068012 і дадаць сваіх думак. Асабліва варта улучыць, што ўжо ў першай ітэрацыі патрэбна падпіска, у другой, напрыклад, збор данатаў.

Там ёсць тры пункты, якія варта прасці, каб разлічыць сілы каманды.

**Comment by rielas** [comment]
Я хацеў бы праясніць два моманты:

1. Я не прэтэндую на лідэрства, ці нейкую іншую асаблівую ролю ў праекце. Таму:

2. Не прэтэндую на тое, каб маё слова было вырашаючым, ці мой код нельга было выдаліць.

Я зрабіў чарнавы варыянт сайта ў першую чаргу для таго, как настроіць devops pipeline. Таму гэты сайт можна лічыць толькі першым прыбліжэннем.

Калі нешта там не адпавядае абранай архітэктуры - смела выдаляйце гэта.

**Comment by rielas** [comment]
Інструкцыю дадам, калі настрою адмінку ў адпаведнасці з user stories

**Comment by rizomaa** [comment]
@rielas насмрэч было б добра каб прэтэндаваў=) бо мы бы хутчэй вырашалі задачы. але акей твой выбар.

я паспрабую паскорыць @Crashtown каб у нас з'явіліся апісаныя юзэр сторы як мага хутчэй

**Comment by rizomaa** [comment]
тут усё яшчэ актуальна. гайд менавіта для рэдактараў.
1. рэгістрацыя.
2. публікацыя і рэдагаванне.
3. абмежаванні і спецыфіка (калі яны ёсць)

**Comment by rielas** [comment]
Пачаў [тутака](https://github.com/konstbel/landing/wiki/%D0%AF%D0%BA-%D0%BF%D1%80%D0%B0%D1%86%D0%B0%D0%B2%D0%B0%D1%86%D1%8C-%D0%B7-%D0%B0%D0%B4%D0%BC%D1%96%D0%BD%D0%BA%D0%B0%D0%B9). Далучайцеся, у каго ёсць пісьменніцкія схільнасці.

**Comment by rizomaa** [comment]
@rielas трохі дадаў структуры

**Comment by rizomaa** [comment]
@alg3rd прывітанне,

Я зараз у адмінцы. Пара каментароў і пытанняў

1. Зайшоў на старонку пра нас. Убачыў html з шабланізацыяй

![Selection_001](https://user-images.githubusercontent.com/9870374/77819464-11b6b200-70ec-11ea-86f9-21768f57521a.png)

Пакажы, гэта бага, або рэдактарам трэба будзе месць справу з таким кодам?

2.  Якія абмежванні на заліўку фота пра Media Manager ?

3. Калі рэдактар на старонцы рэдагавання паста, як яму трапіць на агульны спіс? Ці ёсць хлебныя крошкі?

4. Ці будзе пэджынэйшн для пастоў у адмінцы і ў самім блогу?

Можа яшчэ што трапіць на вока. У так у прынцыпе варта ужо пілоціць

Калі будзеш пісаць гайд, дадай яго калі ласка [сюды](https://github.com/konstbel/landing/wiki/%D0%AF%D0%BA-%D0%BF%D1%80%D0%B0%D1%86%D0%B0%D0%B2%D0%B0%D1%86%D1%8C-%D0%B7-%D0%B0%D0%B4%D0%BC%D1%96%D0%BD%D0%BA%D0%B0%D0%B9)

**Comment by rizomaa** [comment]
@alg3rd знайшоў гайд па рэдагаванн.

1. Крок 4. Варта прыбраць Канстытуцыю.бел Каб у рэдактараў не узнікала блытаніны? 
2. Крок 7. Лепей дадаць скрын, каб не было заблытвання. Бо мне прыйшлося зажмурыцца) 
![Selection_003](https://user-images.githubusercontent.com/9870374/77820021-40cf2280-70f0-11ea-9151-5b267b32cc00.png)
4. А што гэта за пустое месца? 
![Selection_006](https://user-images.githubusercontent.com/9870374/77820037-60664b00-70f0-11ea-88de-5bcfad2a45eb.png)
5. Крок 8. Не зразумелі "загрузкі" чаго паказвае кальцо злева.
6. Схавай калі ласка доступ рэдактарам для розных канфігурацыйных функцый. Ці лічыш гэта норм пакінуць? Чаму? 
![Selection_007](https://user-images.githubusercontent.com/9870374/77820105-dff41a00-70f0-11ea-888b-bfc066a761bb.png)

**Comment by alherd-by** [comment]
@rizomaa У тебя доступ администратора.

**Comment by rizomaa** [comment]
> @rizomaa У тебя доступ администратора.

@alg3rd а якІя ролі ёсць яшчэ?

**Comment by alherd-by** [comment]
- developer
- editor 
- administrator

**Comment by alherd-by** [comment]
@rizomaa 
Сообщение - 1
1. Это костыль на данном этапе. Если напрямую вставлять ссылки на изображения верстка поедет. Это компромиссный вариант, чтобы с одной стороны можно было редактировать контент нетехнарями, а с другой чтобы была в порядке верстка.
2. Насколько есть ограничения у github. Это все по итогу заливается в репозиторий.
3. Все посты в одном списке. Хлебные крошки неактуальны.
4. Пагинация реализована

Сообщение - 2 
1. Убрал
2. Добавил
3. Редактор
4. Добавил пояснения
5. У редакторов это не будет видно

**Comment by rizomaa** [comment]
@alg3rd дадаў структуру гайду. 

Можаш апісаць абмежаванні (памеры, вага) на заліўку медыя кантэнта, асабліва фота. Прыклад, яны зальюць фота 5-10 мегабайт... ці гэта норм на твой погляд, дапускаем?

https://github.com/konstbel/landing/wiki/Як-працаваць-з-рэдагаваннем-кантэнту

**Comment by alherd-by** [comment]
@rizomaa добавил
