### ISSUE TITLE
Абраць тэхналогіі для першай ітэрацыі

### ISSUE THREAD

**Issue by rizomaa** [konstbel/landing#3]
1. Блог
2. Старонкі лэндынга
3. Рассылка (падпіска + пушпаведамленні)

**Comment by rizomaa** [comment]
1. Прапанова: Вордпрэс
2. Пытанне: Колькі удзельнікачаў чакецца на рэдагаванне?
3. Статычны сайт прасцей хосціць і цяжэй заваліць.
4. Прапанова https://jamstack.org/
5.

**Comment by rizomaa** [comment]
Перамяжоўваецца 
https://github.com/konstbel/landing/issues/15

**Comment by rizomaa** [comment]
@ioann-claudius калі ласка апішы тут тэхналогію для вёрсткі

**Comment by rizomaa** [comment]
@ioann-claudius @rielas дадаў вас сюды, бо вы пачалі найбольш спрычыняцца да кода=) калі ласка натуйце свае думкі

**Comment by ghost** [comment]
Предлагаю использовать для front-end React с библиотекой React-Static.
Я вижу в этом такие преимущества:

- Single Page Application - обеспечит лучший user experience по сравнению с многостраничным сайтом. Страница загружается только один раз, поэтому скорость и отзывчивость приложения будут выше. Как мне кажется, это окажется решающим для пользователей, пользующихся мобильной версией, каких сегодня большинство.
- Масштабируемость - хоть мы на данном этапе вычеркнули пункт масштабируемости, хочу обратить внимание на то, что с ростом проекта потенциальный выигрыш от использования React вместо набора html/css/js будет только расти. React использует модульный подход, таким образом повышая количество повторно используемого кода и значительно облегчая его сопровождение.
- Упрощение серверной стороны - мы можем перенести часть логики (как минимум ответственную за переход по страницам) на клиентскую сторону.
- [React-static ](https://github.com/react-static/react-static)- специально создан для создания статичных сайтов. Является 100% SEO friendly. Принцип работы и плюсы изложены в этой [статье](https://medium.com/@tannerlinsley/%EF%B8%8F-introducing-react-static-a-progressive-static-site-framework-for-react-3470d2a51ebc)

Недостатки:
- Бо́льшие затраты времени для разработки на первых этапах. Верстка запланированных 3х страниц с помощью html/css/js займёт меньше времени
- (Мне будет необходима) Дополнительная работа с документацией с целью подключить React-Static
- Обязательное знание/ желание изучить React для потенциального front-end разработчика

**Comment by rielas** [comment]
Відавочна, што асноўны цяжар распрацоўкі, ляжа на плечы @ioann-claudius. Таму я б давяраў яму ў выбары тэхналогіі. У мяне толькі два пытанні:

1. Ці інтэгруецца `react-static` з `netlify`? Мне падаецца, што гэта найпрасцейшы спосаб забяспечыць адмінку.

2. Час зборкі - даволі крытычны. Бо `hugo` збіраецца меней секунды - гэта значыць пастаўка займае максімум паўхвіліны. Гэта вельмі важны UX параметр для рэдактараў.

**Comment by alherd-by** [comment]
Я считаю нам не нужен react и тем более на главном сайте. На первом этапе может не понадобиться JS в принципе.
У нас блог, а не веб-приложение.
В админке - да. Там скорее всего со временем надо будет делать сложные интерфейсы и там уже стоит применять такого рода инструменты.

> Single Page Application - обеспечит лучший user experience по сравнению с многостраничным сайтом

Это очень спорное утверждение.
Тут хорошо расписаны основные минусы SPA https://adamsilver.io/articles/the-disadvantages-of-single-page-applications/ 
SPA не является примером хорошей архитектуры. 

Hugo выполняет все те же функции, что и react-static кроме сборки JS.

**Comment by ghost** [comment]
> Ці інтэгруецца react-static з netlify? Мне падаецца, што гэта найпрасцейшы спосаб забяспечыць адмінку.

Да, React интегрируется с netlify. Отдельной необходимости интегрировать React-Static нет.

>Час зборкі - даволі крытычны. Бо hugo збіраецца меней секунды - гэта значыць пастаўка займае максімум паўхвіліны. Гэта вельмі важны UX параметр для рэдактараў.

В этой [статье](https://www.netlify.com/blog/2019/01/17/how-to-scale-massive-react-static-sites-with-incremental-builds/) разбирается взаимодействие с React-Static. Говорят о промежутке от 20 секунд до 5 минут.

> Я считаю нам не нужен react и тем более на главном сайте. На первом...

Да, это хорошие доводы. Только мне кажется, что архитектура React, напротив, является более удобной, так как его компоненты представляют собой хорошо инкапсулированные сущности. А однонаправленный поток данных защищает от ошибок.
Впрочем, как я уже говорил, выбор технологии не является для меня принципиальным. Точно так же с радостью соглашусь на стандартный набор без фреймворков.

**Comment by rizomaa** [comment]
@rielas прывітанне, апішы калі ласка, як працаваць з прапануемай адмінкай на гэтым хостынгу
http://confident-ardinghelli-605279.netlify.com

**Comment by rizomaa** [comment]
![Selection_020](https://user-images.githubusercontent.com/9870374/74049639-96872880-49e5-11ea-993e-c30f228f59ed.png)
бо вылазіць вось такая памылка пры лагіне праз гітхаб, хаця маю адмна і онэра на гэты рэпазіторый

**Comment by rizomaa** [comment]
Мы прарабілі частку парцы асабліва па першаснай архітэктуры. Зараз важна 

- [x] 1. Мець архітэктуру https://github.com/konstbel/landing/issues/30
- [x] 2. Мець юскейсы (або юзэрсторы) - https://github.com/konstbel/landing/issues/31 для: рэдактараў, адмінаў, рассыльшчыкаў, наведвальнікаў стайта(атрымальніка рассылкі)  тут часткова для адной ролі ёсць https://github.com/konstbel/landing/issues/29#issue-562074475
- [ ] 3. Падлік часу на першую ітэрацыю па тэхналогіям, якія магчыма абраць.

Па гэтым пунктам  мяне тут найбольш пытанняў засталося, асбліва 3 пункт. Пакуль адчуваю тут самая белая пляма)

@alg3rd @Crashtown

**Comment by rizomaa** [comment]
Прапанаваны для рассылкі: 

1. Прапанова ад @alg3rd https://en.wikipedia.org/wiki/GraphQL 
2. https://github.com/marmelab/react-admin ад @alg3rd 
2. тут яшчэ https://github.com/konstbel/landing/issues/7#issuecomment-586577296

**Comment by rizomaa** [comment]
Тэхналогіі з большага абралі. Калі будзе патрэба нешта перамяніць будзем у канкрэтнай задачы, або створым новую тэму.
