### ISSUE TITLE
Скаласці юскейсы для першай ітэрацыі.

### ISSUE THREAD

**Issue by rizomaa** [konstbel/landing#31]
- [ ] - наведвальнік сайта (патэнцыйны валанцёр)
- [ ] - рэдактар
- [ ] - рассыльшчык
- [ ] - атрымлівальнік рассылкі
- [ ] - адмін

**Comment by antonzhyliuk** [comment]
- Наведальнік сайту (бяз ролі)
  - Можа праглядаць старонкі з кантэнтам (навіны, апісаньне руху)
  - Можа пакинуць свой email каб падпісацца на навіны
  - Можа падпісацца на браўзерныя натыфікацыі ад руху
- Рэдактар (роля content-manager)
  - Можа кіраваць навінамі праз асобны інтэрфейс
- Рассыльнік (роля mailing-manager)
  - Можа кіраваць рассылкамі праз асобны інтэрфейс
- Адмін (роля super-admin)
  - Можа кіраваць карыстальнікамі і іх ролямі праз асобны інтэрфейс

**Comment by alherd-by** [comment]
Поскольку статус Done, закрываю
