### ISSUE TITLE
Распрацоўка прататыпы Фронтэнд і бэкэнд (адмінка + API)

### ISSUE THREAD

**Issue by rizomaa** [konstbel/landing#33]

**Comment by rizomaa** [comment]
https://github.com/konstbel/landing/pull/39

**Comment by alherd-by** [comment]
#42

**Comment by rizomaa** [comment]
@alg3rd @antonzhyliuk зачыняю гэту картку, бо вырашылі, што ў якім накірнку рухаемся. дзякуй.
