### ISSUE TITLE
Як далучыцца да працы над статычнымі старонкамі?

### ISSUE THREAD

**Issue by rizomaa** [konstbel/landing#49]
Дзя ляжаць:

- [x] Кантэнт
- [x] Шаблоны
- [ ] Як удзельнічаць у распрацоўцы

Тут пачата праца над [гайдам](https://github.com/konstbel/landing/wiki/%D0%AF%D0%BA-%D0%BF%D1%80%D0%B0%D1%86%D1%83%D0%B5%D0%BC-%D0%BD%D0%B0%D0%B4-%D1%81%D1%82%D0%B0%D1%82%D1%8B%D1%87%D0%BD%D1%8B%D0%BC%D1%96-%D1%81%D1%82%D0%B0%D1%80%D0%BE%D0%BD%D0%BA%D0%B0%D0%BC%D1%96-%D1%96-%D0%B1%D0%BB%D0%BE%D0%B3%D0%B0%D0%BC)

**Comment by rizomaa** [comment]
@rielas @alg3rd калі ласка звярніце увагу, што неабходны просты гайд для апісання як далучыцца да распрацоўкі

**Comment by alherd-by** [comment]
Я добавил описание как добавить верстку и добавил пример темы #63 
Дальше работа продолжиться когда мы определимся с версткой. Потому что после этого структура проекта измениться и тогда мануал будет расширен.

**Comment by rizomaa** [comment]
@alg3rd выдатна. скажы зараз гэта старонка = галоўны гайд па шаблонам старонак (як далучыцца, пра нас) + блога? 

https://github.com/konstbel/landing/wiki/Як-працуем-над-статычнымі-старонкамі-і-блогам

**Comment by alherd-by** [comment]
Без блога

**Comment by rizomaa** [comment]
@alg3rd прывітанне,

Абнаві калі ласка [тут](https://github.com/konstbel/landing/wiki/%D0%AF%D0%BA-%D0%BF%D1%80%D0%B0%D1%86%D1%83%D0%B5%D0%BC-%D0%BD%D0%B0%D0%B4-%D1%81%D1%82%D0%B0%D1%82%D1%8B%D1%87%D0%BD%D1%8B%D0%BC%D1%96-%D1%81%D1%82%D0%B0%D1%80%D0%BE%D0%BD%D0%BA%D0%B0%D0%BC%D1%96-%D1%96-%D0%B1%D0%BB%D0%BE%D0%B3%D0%B0%D0%BC) інфармацыю з
1. годна апошнім пераканфігураваннем адмінкі
2. праве ці ўсяго там дастаткова для далучэння новых людзей на вёрстку 

У мяне асноўнае пытанне як далучаць новых людзей

1. Чалавек зацікавіўся вярстаць.
2.1. Якія крокі яму трэба зрабіць каб ён, яна маглі ўзяць незавярстаную старонку.
2.2. Каб ён,яна маглі правіць багі. 

Буду вельмі удзячны, бо далучыўся яшчэ адзін хлопец, зацелася б каб мы ужо выйшлі на празрысты алгарытм

**Comment by alherd-by** [comment]
Обновил страницу в вики https://github.com/konstbel/landing/wiki/%D0%AF%D0%BA-%D0%BF%D1%80%D0%B0%D1%86%D1%83%D0%B5%D0%BC-%D0%BD%D0%B0%D0%B4-%D1%81%D1%82%D0%B0%D1%82%D1%8B%D1%87%D0%BD%D1%8B%D0%BC%D1%96-%D1%81%D1%82%D0%B0%D1%80%D0%BE%D0%BD%D0%BA%D0%B0%D0%BC%D1%96-%D1%96-%D0%B1%D0%BB%D0%BE%D0%B3%D0%B0%D0%BC
Если будут вопросы - буду дополнять

**Comment by rizomaa** [comment]
пакуль пакіну адкрытай,
1. Структура больш менш зразумела.
2. Дзе кантэнт таксама.
3. Але як пачаць кантрыбиць вааабшчэ не зразумела. 
Я знайшоў нейкі гайд анлайн як працаваць з хуго, але бачна што гэта не вельмі папулярная тэзналогія. 
https://snipcart.com/blog/hugo-tutorial-static-site-ecommerce

Было б добра даць 2-3 крокі, што трэба каб разгарнуць асяродак працы. дзякуй @alherd-by

**Comment by alherd-by** [comment]
@rizomaa да, распишу поподробнее и добавлю примеров

**Comment by alherd-by** [comment]
Я не знаю, что еще можно сделать в плане документации. Мне не хватает обратной связи, насколько это понятно расписано. 
От меня будет следующее решение:
если появятся желающие выполнить задания по верстке и у них будут вопросы, пусть напишут мне, я тогда объясню непонятные моменты и исходя из этого дополню документацию.
