### ISSUE TITLE
Патрэбная інфраструктура

### ISSUE THREAD

**Issue by rizomaa** [konstbel/landing#5]
Удаклданіць для першай ітэрацыі з улічваннем развіцця

**Comment by rizomaa** [comment]
Такімі сэрвісамі раней карысталіся 
https://github.com/konstbel/landing/wiki/Тэхналогіі,-якія-выкарыстоўваліся-на-папярэдняй-версіі

**Comment by rizomaa** [comment]
адаслаў запыт згодна нашай размове ў суботу
VPS 1 гіг аперацыйная сістэма Ubuntu 18
@alg3rd @Crashtown

**Comment by rielas** [comment]
> адаслаў запыт згодна нашай размове ў суботу
> VPS 1 гіг аперацыйная сістэма Ubuntu 18
> @alg3rd @Crashtown

А што плануецца размесціць на гэтым хостынгу? Пытаюся, таму што для статычных сайтаў ёсць і бясплатныя рашэнні, кшталту Netlify. Што прапануе Netlify дарам:

> For free accounts:
>     Network Bandwidth: 100GB/month — Soft
>     Storage: 100GB — Soft
>     API requests: 500 requests/minute, 3 deploys/minute* — Hard

Што мы атрымліваем ад гэтага хостынга:

- ён адаптаваны для статычных старонак, а значыць мае CDN;
- маем бясплатны дамен konstbel.netlify.com;
- маем магчымасць рабіць перадпрагляд для PR-аў;
- сэрвіс identity для адмінкі;
- хуткія аўта-дэплоі - там ужо настроены hugo. Дэплой займае максімум паўхвіліны;
- ёсць магчымасць дасылаць POST запыты (HTML формы і нават AJAX) і бачыць іх у Netlify dashboard;
- A/B тэсты на базе двух git галін;

**Comment by alherd-by** [comment]
@rielas дабы уточнить. То что мы запросили хостинг это для админки, т.к. нам надо делать рассылки. 
Продакшен будет на netlify

**Comment by rielas** [comment]
Давайце мы і асноўны дамен перанясем на https://konstbel.netlify.com. Галасуйце лайкамі ці дызлайкамі, ці наўпрост пішыце меркаванне

**Comment by rizomaa** [comment]
1/ @rielas якія там dns?
2/ @alg3rd На якім (пад)дамене будзе адмінка?

**Comment by rielas** [comment]
CNAME konstbel.netlify.com

**Comment by rizomaa** [comment]
@rielas зрабіў запыт, буду трымаць у курсе
