### ISSUE TITLE
Синхронизация работы по верстке

### ISSUE THREAD

**Issue by alherd-by** [konstbel/landing#60]
На данный момент у нас есть три варианта верстки:
1. от меня @alg3rd . https://svezhyvecer.by
2. @sasaafanasienka - https://konstbel.github.io/landing/
3. @kate-pote 

Нам нужно выбрать с каким вариантом работаем дальше. Вариант 1 на данным момент является наиболее готовым: есть мобильная и десктопная версия, помимо главной страницы есть и другие страницы. В этом варианте используется bootstrap с scss. Там много моментов которые нужно дорабатывать т.к. моим основным профилем не является верстка. 

Что скажете @sasaafanasienka @kate-pote ? Согласны ли вы адаптировать текущий продакшен -вариант или выбрать один из ваших? Достаточно ли гибок bootstrap?

**Comment by kate-pote** [comment]
вторая верстка более проработана с точки дрения стилей, так же как и моя. В своей разработке я так же использовала bootstrap и scss. И она тоже более проработанная. Сегодня я залью готовую версию для 768px.

**Comment by rizomaa** [comment]
@kate-pote вітаю па вашаму пытанню

"
Katerina, [06.03.20 17:03]
Нужна ли вам ещё верстка моя? Я вижу уже выложили другую версию главной страницы

Rizoma T, [07.03.20 17:35]
Прывітанне,

Добрая тэндэнцыя заўважыў вашы каментары на гітхабе. Дзякуй за пулрэквэсты.

Распавядаю сітуацыю. Хлопец, які найбольш актыўны Павел (@alg3rd) па распрацоўцы перастаў чакаць і зрабіў самастойна, наколькі мог. Яшчэ далучыўся адзін хлопец Аляксандр таксама, каб папрацаваць з вёрсткай. 

Пакуль такі сцэнар:

1. У бліжэйшы час Павел (alg3rd) вызначыць дакументацыю па працы з існуючым разгорнутым сайце.
2. Вы азнаёміцеся і прыміце рашэнне, ці гатовыя працягваць кодзіць (патрэбна будзе інтэграцыя на hugo шаблоны).
3. Калі так, мы пагутарым з Аляксандрам (іншым кантрыбютарам: @sasaafanasienka) і падзелім працу, каб было сінхранізавана і праца не перасякалася.

Падыходзіць?

Калі так - працягвайце працу над дэсктопнай версіяй і старонкай "пра нас".

зы
Наогул праца перасякнулася па шмат, якім прычынам:
1. Мы доўга чакалі раскачкі па вёрстцы.
2. Адзін чалавек адваліўся ад працы. Узнікла рызыка для руха праекта.
3. Мы толькі знаёмімся толькі зараз выбудоўваем працэс узаемадзеяння і давер.

Спадзяюся на паразуменне і рухаемся далей
"

**Comment by sasaafanasienka** [comment]
Кто мне может объяснить, откуда мне брать текущую последнюю версию для доработки. Насколько я понимаю, вносились какие-то правки для hugo в том числе и в мою верстку.

**Comment by alherd-by** [comment]
@sasaafanasienka ветка dev - themes/sasaafanasienka

**Comment by rizomaa** [comment]
@sasaafanasienka слушнае пытанне.

@alg3rd зараз на dev ляжаць ужо шаблоны. @sasaafanasienka робіць голую вёрстку. 
раскладзі тут па палічках куды класці голую вёрстку, каб праца была аптымізавана

**Comment by alherd-by** [comment]
@sasaafanasienka делай пожалуйста, весь свой прогресс делай в отдельной папке в themes/sasaafanasienka_static. Там не будет изменений пока не закончишь.
Сорри, я поторопился твою работу объединять с шаблонами.

**Comment by sasaafanasienka** [comment]
Так я, кажется, уже сделал верстку

**Comment by rizomaa** [comment]
@sasaafanasienka можаш спасылку на гэты рэквэст паказаць? бо бачу апошни рэквэст  merged 17 days ago 

Як разумею апошнія праўкі не былі пад ПР https://github.com/sasaafanasienka/landing/tree/dev/themes/sasaafanasienka

**Comment by alherd-by** [comment]
@sasaafanasienka может есть какие-то вопросы?

**Comment by sasaafanasienka** [comment]
Я видимо в гите чего-то не понимаю, делаю коммит - он вроде создается, все добавляется и т.д., но на гитхабе потом найти ничего не могу.
Может вы тут мою верстку заберете https://cloud.mail.ru/public/4ZKT/3df7hBTqo ?

**Comment by alherd-by** [comment]
@sasaafanasienka Спасибо за проделанную работу.

Я откатил все свои измения с твоими файлами. Верстка адаптированная под хьюго теперь лежит отдельно в sasaafanasienka_hugo. Результат теперь виден здесь - https://konstbel.github.io/landing/
> Я видимо в гите чего-то не понимаю, делаю коммит - он вроде создается, все добавляется и т.д., но на гитхабе потом найти ничего не могу.

Потому что был пуш коммитов не в основной репозиторий, а в [форк](https://git-scm.com/book/ru/v2/GitHub-%D0%92%D0%BD%D0%B5%D1%81%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D0%BE%D0%B1%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%B0-%D0%B2-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D1%8B).

https://github.com/konstbel/landing/pull/69 Я смерджил твои изменения.
