### ISSUE TITLE
Прапаную змяніць выгляд элементаў галоўнай старонкі (кніга і арнамент)

### ISSUE THREAD

**Issue by alherd-by** [konstbel/landing#61]
Версия: Десктоп

Стоит ли немного переделать два момента связанные с главной страницы: 
1) уменьшить размер книги 
2) переместить арнамент в блок "Как приесоединится"

Из-за совокупности этих вещей получается то, что блок "Как присоединится" выталкивается на второй экран и создает неудобства в UX плане - нужно долго листать страницу.
Для сравнения другой вариант(с неидеальной версткой):
![image](https://user-images.githubusercontent.com/1499176/76143163-26240380-6086-11ea-9540-d6b29f3dfbfb.png)

Для мобильной версии это не актуально.

**Comment by syromolotovpavel** [comment]
@alg3rd 

По поводу книги
Размер книги менять не стоит. Но ее можно увести в право, чтобы часть ее была скрыта. Как на прототипах.

По поводу блока "как присоединиться" и орнамента.
Я перепроверил на разрешении 1280x800 и 1920x1200 и на сколько я вижу, скролить много не нужно.
Тут важно понимать, что мы показываем пользователю часть контента и дальше он понимает что дальше что-то есть.

Другой вопрос, если удобней и быстрее для этой версии сайта сделать расположение контента блока "как присоединиться" и орнамента горизонтально, то ок, я, конечно, не против.
